# Generated by Django 4.2 on 2024-11-19 22:40

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_fa', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('first_name_fa', models.CharField(max_length=20, null=True)),
                ('first_name_en', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('last_name_fa', models.CharField(max_length=30, null=True)),
                ('last_name_en', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='title')),
                ('title_fa', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=55, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='sliders', verbose_name='image')),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='order')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'sliders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone', models.CharField(max_length=15)),
                ('nationalـcode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, default='Iran', max_length=50)),
                ('country_fa', models.CharField(blank=True, default='Iran', max_length=50, null=True)),
                ('country_en', models.CharField(blank=True, default='Iran', max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('state_fa', models.CharField(blank=True, max_length=50, null=True)),
                ('state_en', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('city_fa', models.CharField(blank=True, max_length=50, null=True)),
                ('city_en', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('address_fa', models.CharField(blank=True, max_length=250, null=True)),
                ('address_en', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_fa', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description_fa', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description_en', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count_sold', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='products')),
                ('star', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_special', models.BooleanField(default=False)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('category_en', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('category_fa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address_fa', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address_en', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 11, 20, 2, 10, 54, 999758))),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
